# # # # # # # # # # # # #   COMPOSE FILE   # # # # # # # # # # # #

services:

  # # # # # # # # #   DEVCONTAINER   # # # # # # # # #
  ur_container: # Nombre del servicio
    # Construcción del contenedor
    image: universalrobots/ursim_e-series:5.23

    # Cómo se llamará el contenedor generado
    container_name: ur_container

    # El contenedor compartirá la misma interfaz de red del host
    network_mode: host

    ports:
      - "5900:5900"
      - "6080:6080"
      - "29999:29999"

    environment:
      - ROBOT_MODEL=UR10

    # Mapea el workspace local dentro del contenedor
    volumes:
      - /dev:/dev
      - /opt/datos_usb:/ursim/programs

    command: ["/bin/bash", "-il"]
    tty: true
    stdin_open: true
    privileged: true # Mantenemos esto para que /dev funcione bien con tus USBs

  # ----------------------------------------------------------------